### ISSUE TITLE
Doesnt work in horizontal scrollview

### ISSUE THREAD

**Issue by AFMW** [netceteragroup/skele#114]
Is it possible to implement it in a horizontal scrollview?
when the scrollview is without that prop works perfectly but with that prop doesnt work :(

**Comment by bevkoski** [comment]
@AFMW, viewport awareness currently works only for vertically scrollable views.

[`Viewport.Tracker`](https://github.com/netceteragroup/skele/blob/master/packages/components/src/viewport/tracker/index.js) and [`Viewport.Aware`](https://github.com/netceteragroup/skele/blob/master/packages/components/src/viewport/aware/index.js) will need to be extended to support horizontal views. Feel free to experiment with them and submit a pull request!

**Comment by bevkoski** [comment]
Hi @AFMW! Support for horizontally scrollable views is available since `v1.0.0-alpha.40`, thanks to @n-sviridenko. Here is a working Snack that you can test out: https://snack.expo.io/By2z0s3gB.

**Comment by actuallymentor** [comment]
Note, this does not work without using the placeholder functionality. See [this snack](https://snack.expo.io/@makesomenoise/9417d7).
