### ISSUE TITLE
Override inViewport behaviour

### ISSUE THREAD

**Issue by swparkaust** [netceteragroup/skele#152]
I'm using `Viewport.Aware` & `Viewport.WithPlaceholder` with `react-navigation`.
Currently when I navigate to different routes/screens than the one containing scroll view `inViewport` of my viewport aware components remains `true`, even though they are not.

`react-navigation` has `isFocused` prop which tells you the focused state of a screen.
Is there a way to pass in such prop to supplement `inViewport` so that I can keep using `Viewport.WithPlaceholder`, while not having to separately handle the case when the screen is not focused?

**Comment by ognen** [comment]
Hi @swparkaust, 

Currently, there is no way to do what you are asking. As we like to have components that do one thing only, I would suggest going the way of composing write a new HoC that does what you need and compose it into the chain. 

The end result should look like:
```javascript
import { Image, View } from 'react-native'
import { Viewport } from '@skele/components'
import { ScreenState } from './screen-state' // this is the HoC you need to write

const Placeholder = () =>
  <View style={{ width: 50, height: 50, backgroundColor: 'darkgrey' }} />

const VAImgWithPlaceholder =
  Viewport.Aware(
     ScreenState.Aware(
       Viewport.WithPlaceholder(Image, Placeholder)
     )
  )
```

`ScreenState.Aware()` should produce a HoC that: 
* takes the `inViewport` prop (see [this line](https://github.com/netceteragroup/skele/blob/ec864de86451f3d1b923de311cd69633644361e8/packages/components/src/viewport/aware/index.js#L114)) and combines it in with the `isFocused` information from react-navigation
* passes this modified inViewport data down to the wrapped component
* you will need to employ a context provider to pass the `isFocused` info down the tree.

Hope this helps.
